### ISSUE TITLE
No User Input Handling

### ISSUE THREAD

**Issue by TRemigi** [ZQWhiting/media4u#11]
### Make sure user has typed a search term in the form before passing along to appropriate media fetch handler function

- conditional statement should be placed after searchTerm variable is defined, and before selectedMedia is defined:

    If (!searchTerm) {Ask user to put something in search term field. Per assignment requirements, this cannot be an alert, so modal is likely};
    return;

**Comment by ZQWhiting** [comment]
We should wait on this one until we get the fetch functions all set up and update the form accordingly.

**Comment by TRemigi** [comment]
Agreed!
