### ISSUE TITLE
HTML Base display for API response

### ISSUE THREAD

**Issue by ZQWhiting** [ZQWhiting/media4u#12]
All the HTML elements of the display section that don't need to be dynamically created.

## Question
* Should we display the lists in a separate HTML file, or just below the hero?

**Comment by TRemigi** [comment]
I think just below the hero is fine but let's hear what others have to say. If we do a single page however, it would be cool if we could make it automatically scroll to the results.

**Comment by ZQWhiting** [comment]
I was looking at the possibility of an autoscroll, and it seem pretty easy to pull off. Just need to put a `window.scrollTo()` function somewhere.

**Comment by ZQWhiting** [comment]
Seems like a pretty easy addition to add a `windows.scrollTo()` function.
